# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: The Docing of Isaac
site_url: https://isaacyip.com/
site_author: Isaac Yip
# site_description: >-
#   Write your documentation in Markdown and create a professional static site in
#   minutes – searchable, customizable, in 60+ languages, for all devices

# Repository
repo_name: yip102011/my_mkdocs
repo_url: https://github.com/yip102011/my_mkdocs

# Copyright
copyright: Copyright &copy; 2022 - 2024 Isaac Yip

# dev_addr: '0.0.0.0:8000'

# Configuration
theme:
  name: material
  language: en
  # custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.instant
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# extra_javascript:
#   - javascripts/extra.js
# extra_css:
#   - stylesheets/extra.css
# .
# ├─ docs/
# │  └─ stylesheets/
# │     └─ extra.css
# │  └─ javascripts/
# │     └─ extra.js
# └─ mkdocs.yml

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
        - en
        - zh
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
      ## curl https://raw.githubusercontent.com/fxsjy/jieba/master/extra_dict/dict.txt.big -o dict.txt.big
      ## curl https://raw.githubusercontent.com/fxsjy/jieba/master/extra_dict/dict.txt.small -o dict.txt.small
      # jieba_dict: dict.txt.small
  - blog:
      enabled: true
      # blog_dir: blog
      blog_dir: .
      blog_toc: true
      post_date_format: yyyy-MM-dd
      # post_url_format: "{slug}"
      post_url_format: "{slug}"
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      # post_readtime_words_per_minute: 300
      archive: false
      # archive_toc: true
      # archive_date_format: yyyy
      # archive_url_date_format: yyyy
      # archive_url_format: "archive/{date}"
      # archive_pagination: false
      # archive_pagination_per_page: 5
      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_if_single_page: false
      pagination_keep_content: false
  # - social:
  #     enabled: true
  #     cards: true
  - tags:
      enabled: true


  # - minify:
  #     minify_html: true

# Hooks
# hooks:
#   - material/.overrides/hooks/translations.py

# Customization
extra:
  # generator: false
  annotate:
    json: [.s2]
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yip102011

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Page tree
# nav:
#- Home: index.md
# - Getting started:
#   - Installation: getting-started.md
#   - Creating your site: creating-your-site.md
#   - Publishing your site: publishing-your-site.md
#   - Customization: customization.md
#   - Browser support: browser-support.md
#   - Philosophy: philosophy.md
#   - Alternatives: alternatives.md
#   - License: license.md
#   - Changelog:
#     - changelog/index.md
#     - How to upgrade: upgrade.md
#   - Contributing:
#     - contributing/index.md
#     - Reporting a bug: contributing/reporting-a-bug.md
#     - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#     - Requesting a change: contributing/requesting-a-change.md
#     - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
#   - Guides:
#     - Creating a reproduction: guides/creating-a-reproduction.md
# - Setup:
#   - setup/index.md
#   - Changing the colors: setup/changing-the-colors.md
#   - Changing the fonts: setup/changing-the-fonts.md
#   - Changing the language: setup/changing-the-language.md
#   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#   - Ensuring data privacy: setup/ensuring-data-privacy.md
#   - Setting up navigation: setup/setting-up-navigation.md
#   - Setting up site search: setup/setting-up-site-search.md
#   - Setting up site analytics: setup/setting-up-site-analytics.md
#   - Setting up social cards: setup/setting-up-social-cards.md
#   - Setting up a blog: setup/setting-up-a-blog.md
#   - Setting up tags: setup/setting-up-tags.md
#   - Setting up versioning: setup/setting-up-versioning.md
#   - Setting up the header: setup/setting-up-the-header.md
#   - Setting up the footer: setup/setting-up-the-footer.md
#   - Adding a git repository: setup/adding-a-git-repository.md
#   - Adding a comment system: setup/adding-a-comment-system.md
#   - Building an optimized site: setup/building-an-optimized-site.md
#   - Building for offline usage: setup/building-for-offline-usage.md
#   - Extensions:
#     - setup/extensions/index.md
#     - Python Markdown: setup/extensions/python-markdown.md
#     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
#   - Dependencies:
#     - setup/dependencies/image-processing.md
# - Reference:
#   - reference/index.md
#   - Admonitions: reference/admonitions.md
#   - Annotations: reference/annotations.md
#   - Buttons: reference/buttons.md
#   - Code blocks: reference/code-blocks.md
#   - Content tabs: reference/content-tabs.md
#   - Data tables: reference/data-tables.md
#   - Diagrams: reference/diagrams.md
#   - Footnotes: reference/footnotes.md
#   - Formatting: reference/formatting.md
#   - Grids: reference/grids.md
#   - Icons, Emojis: reference/icons-emojis.md
#   - Images: reference/images.md
#   - Lists: reference/lists.md
#   - MathJax: reference/mathjax.md
#   - Tooltips: reference/tooltips.md
# - Insiders:
#   - insiders/index.md
#   - Getting started:
#     - Installation: insiders/getting-started.md
#     - Changelog: insiders/changelog.md
# - Blog:
#   - blog/index.md
#   - 2022:
#     - blog/posts/blog-support-just-landed.md
#     - blog/posts/chinese-search-support.md
#   - 2021:
#     - blog/posts/the-past-present-and-future.md
#     - blog/posts/excluding-content-from-search.md
#     - blog/posts/search-better-faster-smaller.md
